# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNMParticle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNMParticle
  pod 'React', :path => '../node_modules/react-native'
end
